### ISSUE TITLE
Add a Rollup-compatible ES modules build

### ISSUE THREAD

**Issue by gaearon** [sindresorhus/symbol-observable#9]
Redux depends on this library now, which [breaks ES modules build](https://github.com/reactjs/redux/issues/1754) of Redux. It would be great if we could offer an ES modules build of this library in `/es/` and point `jsxnext:main` to it.

**Comment by benlesh** [comment]
Seems reasonable

**Comment by benlesh** [comment]
@gaearon I just thought of something (Although I haven't looked into this yet). Recreating this with ES6 will need to be done by hand I think, because if I rewrite it in ES6, the transpiled CJS will require it to be used like `require('symbol-observable').default` I think. That will be a breaking change for everyone using this. :\

**Comment by jamestalmage** [comment]
If you are **only** exporting a default. You can use this: https://www.npmjs.com/package/babel-plugin-add-module-exports.

There were good reasons babel changed the behavior though: https://phabricator.babeljs.io/T2212#57710

**Comment by gaearon** [comment]
> You can use this: https://www.npmjs.com/package/babel-plugin-add-module-exports.

Yeah, this is what I had in mind. I haven’t tried it though.

**Comment by benlesh** [comment]
@jamestalmage oh, thanks, I didn't know about the plugin. I just knew the reasons babel wouldn't do it. It's probably totally safe for this project, since there's just the one export.

**Comment by PalermoD** [comment]
Thanks that worked great
